### ISSUE TITLE
Added notes are displayed but link to note page throws 404.

### ISSUE THREAD

**Issue by jaltgen** [Jekyll-Garden/jekyll-garden.github.io#19]
When adding a note to the _notes/Public/ folder with a name "Animals.md", jekyll detects it and updates the feed for this collection. The element is then displayed in the feed, with preview and everything. So far so good.

When I click on the title link to /notes/Animals, the 404 page is thrown. Jekyll server also reports **"ERROR `/notes/Animals' not found.**

Any pointers?

**Comment by jaltgen** [comment]
For example, this **Dog.md** file works under localhost:4000/notes/Dog
~~~
---
title : Dog
notetype : feed
date : 25-03-2022
---

Kalle is one of my [[Animals]]
~~~

While this **Learning.md** file does not work under localhost:4000/notes/Learning

~~~
---
title : Learning
notetype : feed
date : 29-03-2022
---


#atomic
----
- [ ] #todo write what you know about learning
# Abstract
Principles such as:
- easy to difficult
- slow to fast
- continuous repetition
- application over cramming

# Relates To

What does this atomic piece of info relate to.
~~~


I'm currently running this in a local docker for development, the base_url is set to "/", so URLs should be correct (and are working for other notes.

**Comment by jaltgen** [comment]
Hm so I did a diff and I only changed the basic settings. However, I restarted the docker and now the error is gone :o

**Comment by hfactor** [comment]
Glad!

**Comment by timbergrizz** [comment]
I have similiar errors on github pages. it occurs when metadata includes date information.

**Comment by hfactor** [comment]
@timbergrizz : Is it a future date? Then Jekyll won't support that.
