### ISSUE TITLE
Could I port this theme to Hugo?

### ISSUE THREAD

**Issue by Sevichecc** [Jekyll-Garden/jekyll-garden.github.io#23]
Thank you so much for such a fantastic, well-thought-out, and beautiful theme! I really love it.

And could I port this theme to Hugo? I'm not sure whether I could do it though……

**Comment by hfactor** [comment]
I wanted to write this on Hugo. The only reason I continued with Jekyll is that I don't have to rewrite everything again. Feel free to fork and use. (Btw, a new version of the theme is available @ hiran.in - Needs some cleanup and I will update this upstream)

**Comment by hfactor** [comment]
_This is not a feature request. Its permission request and the outcome will be a theme outside this repo._
