### ISSUE TITLE
Dockerfile Please

### ISSUE THREAD

**Issue by veerendra2** [Jekyll-Garden/jekyll-garden.github.io#8]
Project maintainers, you can please add `Dockerfile`, I'm not a ruby person, but I like jekyll tool. It is very hard for find gems and other dependencies. Can you please create Dockerfile for local dev

**Comment by hfactor** [comment]
@veerendra2 : Even I am not a ruby person :(. I will try to get this done.

**Comment by gnuanu** [comment]
@veerendra2 This should work https://github.com/Jekyll-Garden/jekyll-garden.github.io/pull/16

**Comment by hfactor** [comment]
Thanks, @gnuanu for the docker file!
