### ISSUE TITLE
GH Pages deploy not working

### ISSUE THREAD

**Issue by mroberts1** [Jekyll-Garden/jekyll-garden.github.io#9]
Can't get this to format properly when deployed on GH Pages, either using the template or forking the repo to my own account. I set the branch to main and saved in the Settings.  Flushed the browser cache (Chrome) but issue persists.

When cloning the repo and installing Jekyll, it builds just fine locally, but when I then push it back up to GH it still won't format the repo on GH Pages.

The last template I tried is at github.com/mroberts1/supreme-couscous

Any idea what the problem might be?

<img width="1421" alt="Screen Shot 2021-10-04 at 8 31 48 AM" src="https://user-images.githubusercontent.com/8925762/135852020-6e6b606f-0ade-4981-9d09-418a2f5d3c34.png">

**Comment by hfactor** [comment]
@mroberts1: Can you change the base URL and try? Its line number 23 of _config.yml

**Comment by mroberts1** [comment]
I tired changing the baseurl to /obsidian (the repo name) but the jekyll site still doesn't build with your theme. The deploy works fine on Netlify so I suspect the problem is jekyll plugins that aren't supported on GH pages.

**Comment by hfactor** [comment]
@mroberts1 : I am running a fork and it's working fine - https://github.com/hfactor/hfactor.github.io

**Comment by llsaboya** [comment]
Same think here. Looks like deploy goes ok but I got a blank page.

**Comment by hfactor** [comment]
@mroberts1 : `baseurl` is used for creating subpath. ie, to host at example.com/obsidian config should be `baseurl: /obsidian` Did you change line 23 - url: "https://jekyll-garden.github.io/" ?

**Comment by hfactor** [comment]
@mroberts1 : Check #11. 
Also, while using subpath, the hyperlinks are breaking. #20 I will sort that out soon.
